In [1]:
import statistics
statistics.mean([1,2,3])

2

docs.python.org

In [3]:
import random
random.randint(10,21)
# l = list(random.randrange(1,10))

10

In [4]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [5]:
pip install numpy

     |████████████████████████████████| 14.5MB 1.3MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np
l = [1,2,3,4]
np.array(l)
randomlist = random.sample(range(10, 30), 20)
print(randomlist)
np.random.randint(1,100,15)

[26, 24, 10, 14, 19, 16, 29, 22, 27, 20, 28, 18, 25, 17, 11, 15, 12, 13, 23, 21]


In [9]:
import numpy as np
a = np.array([1,2,3,4,5,6,])
a[::-5]
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b.argmin())
print(b[0:,1::-1])
#print(any(b > 2 and b<5))


0
[[2 1]
 [5 4]
 [8 7]]


In [11]:
import numpy as np
a = np.arange(0.23,79)
np.stack(a)

array([ 0.23,  1.23,  2.23,  3.23,  4.23,  5.23,  6.23,  7.23,  8.23,
        9.23, 10.23, 11.23, 12.23, 13.23, 14.23, 15.23, 16.23, 17.23,
       18.23, 19.23, 20.23, 21.23, 22.23, 23.23, 24.23, 25.23, 26.23,
       27.23, 28.23, 29.23, 30.23, 31.23, 32.23, 33.23, 34.23, 35.23,
       36.23, 37.23, 38.23, 39.23, 40.23, 41.23, 42.23, 43.23, 44.23,
       45.23, 46.23, 47.23, 48.23, 49.23, 50.23, 51.23, 52.23, 53.23,
       54.23, 55.23, 56.23, 57.23, 58.23, 59.23, 60.23, 61.23, 62.23,
       63.23, 64.23, 65.23, 66.23, 67.23, 68.23, 69.23, 70.23, 71.23,
       72.23, 73.23, 74.23, 75.23, 76.23, 77.23, 78.23])

In [1]:
import pandas as pd
import numpy as np

In [5]:
index = ['a','b','c','d','e']
data = [10,20,30,40,50]
data1 = {2,3,4,5,6}
array = np.arange(100,501,100)
d1 = {'a':5,'b':10,'c':15,'d':20,'e':25}
a = pd.Series(data)
b = pd.DataFrame(data,index)
b

0
a  10
b  20
c  30
d  40
e  50

In [2]:
data1 = {'corona_patients':"A B C D E".split(),'states':"TN KL KA MH GU".split()}
a = pd.DataFrame(data1,index="a b c d e".split())
a

corona_patients states
a               A     TN
b               B     KL
c               C     KA
d               D     MH
e               E     GU

In [4]:
a.values

array([['A', 'TN'],
       ['B', 'KL'],
       ['C', 'KA'],
       ['D', 'MH'],
       ['E', 'GU']], dtype=object)

In [5]:
a.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [6]:
a['states']

a    TN
b    KL
c    KA
d    MH
e    GU
Name: states, dtype: object

In [7]:
a[['corona_patients','states']]

corona_patients states
a               A     TN
b               B     KL
c               C     KA
d               D     MH
e               E     GU

In [14]:
from numpy.random import randn
df = pd.DataFrame(data = randn(5,4),index = 'a b c d e'.split(),columns= 'w x y z'.split())
df.loc['a']

w    0.350979
x    0.841977
y    0.484781
z   -1.591207
Name: a, dtype: float64

In [15]:
df

w         x         y         z
a  0.350979  0.841977  0.484781 -1.591207
b -0.639961 -0.691264 -0.698293  1.298878
c  0.474827 -0.124949 -0.289650 -1.191004
d  0.062704  1.284022  0.722864 -0.873921
e -0.195647  0.546731  1.881202 -1.429914

In [19]:
df.loc['a','x']

0.8419769556409715

In [20]:
df.iloc[:2,:2] 

w         x
a  0.350979  0.841977
b -0.639961 -0.691264

In [21]:
df>0.2

w      x      y      z
a   True   True   True  False
b  False  False  False   True
c   True  False  False  False
d  False   True   True  False
e  False   True   True  False

In [23]:
df['w']>0.2

a     True
b    False
c     True
d    False
e    False
Name: w, dtype: bool

In [24]:
df.loc['a']>0.2

w     True
x     True
y     True
z    False
Name: a, dtype: bool

In [25]:
df[df>0.2]

w         x         y         z
a  0.350979  0.841977  0.484781       NaN
b       NaN       NaN       NaN  1.298878
c  0.474827       NaN       NaN       NaN
d       NaN  1.284022  0.722864       NaN
e       NaN  0.546731  1.881202       NaN

In [33]:
df[df['w']>0.2]

w         x         y         z
a  0.350979  0.841977  0.484781 -1.591207
c  0.474827 -0.124949 -0.289650 -1.191004

In [34]:
df['w'][df['w']>0.2]

a    0.350979
c    0.474827
Name: w, dtype: float64

In [35]:
pwd

'/home/harrish/Downloads/Practise'

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,])
a[::-5]
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [2]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
lst = [3, 4, 5, 20, 5, 25, 1, 3]

lst.pop(1)

lst

[3, 5, 20, 5, 25, 1, 3]

In [12]:
List1 = ["TCS", "IBM", "CTS","WIPRO", "ZOHO"]
List1.insert(4, "MICROSOFT")
List1

['TCS', 'IBM', 'CTS', 'WIPRO', 'MICROSOFT', 'ZOHO']

In [15]:
a = "aSdF"
a.capitalize()

'Asdf'

In [16]:
List = [123, 456, 789, 101112, 131415, 161718, 192021, 222324]

print(List[-5::][::-2])

[222324, 161718, 101112]


In [17]:
D={ 'A':43,'B':56, 'C':67}
D

{'A': 43, 'B': 56, 'C': 67}

In [18]:
a = Dict('A':43,'B':56, 'C':67)
a

SyntaxError: invalid syntax (<ipython-input-18-f1f1309d5c28>, line 1)

In [24]:
values = [[33, 44, 55, 66], [33, 6, 1, 2]]

v = values[0][0]

for row in range(0, len(values)):

    for column in range(0, len(values[row])):

        if v < values[row][column]:

            v = values[row][column]
            print(v)
print(v)

44
55
66
66


In [30]:
l = [1,2,3,4,5]
a = l.reverse


<function list.reverse()>

In [35]:
a= (5,)
# id(l)
id(a)

139774969791040

In [38]:
List1=[1,2,3,4,5,6,7,8,9]

for numbers in List1:

    print(numbers**2, end= " ")

1 4 9 16 25 36 49 64 81 

In [40]:
Disease_name = "corona"

if Disease_name=="corona" or Disease_name=="Corona":

    print("Go!")

else:

    print("Its difficult")

Go!


In [41]:
i = sum = 0

while i <= 4:

    sum += i

    i = i+1

print(sum)

10


In [42]:
d = {00: 'a', 11: 'b', 22: 'c'}

for i in d:

     print(i)



0
11
22


In [45]:
abs(5+i5)

NameError: name 'i5' is not defined

In [47]:
z = complex(5,6)
abs(z)

7.810249675906654

In [48]:
def radian(num):

      num=num

      import math

      return math.isnan(num)

radian(9)

False

In [49]:
def great(string):

      name=string

      if name=='string':

           print("its great")

great()

TypeError: great() missing 1 required positional argument: 'string'

In [51]:
def sqrt(num):

      num=0

import math 
return math.sqrt(num)

sqrt(9)

SyntaxError: invalid syntax (<ipython-input-51-eda22633c2fd>, line 5)

In [52]:
def num(*args):

       return enumerate(*args)

list(num(('123')))

[(0, '1'), (1, '2'), (2, '3')]

In [55]:
def code():

     for numbers in '1234':

           for letters in 'abc':

               print(len(nubers),len(letters))

code().sum()

NameError: name 'nubers' is not defined

In [58]:
def a(*args):
    return sum(*args)
b =(10,10)
a(b)

TypeError: 'int' object is not callable

In [4]:
x = bin(input())
if x =='Ob111OOO':
    print(x)
else:
    print("python object")

0100


TypeError: 'str' object cannot be interpreted as an integer

In [1]:
import pandas as pd

# gets the car which has the highest sales
def getBestSellingCar() :
    print("\nThe best selling car is ")
    print(car_dataframe[car_dataframe.Sales_in_thousands ==car_dataframe.Sales_in_thousands.max()])
    
# gets the car which has the highest sales of the given manufaacturer
def getBestSellingCarByManufacturer(manufacturer) :
    print("\nThe best selling car from the manufacturer "+ manufacturer + " is ")
    print(best_selling_cars[best_selling_cars.Manufacturer == manufacturer])

# reading from car_details.txt file which is given in the question
f = open("car_details", "r")
car_details_list = []
# iterating each lines in text file
for i in f:
    # appending each row of car details and splitting using double space
    car_details_list.append(i.strip().split('  '))
    
# converting the car_details_list to a dataframe ignoring the first row as it has column names
car_dataframe = pd.DataFrame(car_details_list[1:])
# setting columns for car dataframe
car_dataframe.columns = [i.strip() for i in car_details_list[0]]
# converting 'Sales_in_thousands' from string to float
car_dataframe['Sales_in_thousands'] = car_dataframe['Sales_in_thousands'].astype(float) 
# grouping the car dataframe by manufacturer with highest sales into a new dataframe 'best_selling_cars'
best_selling_cars = car_dataframe.loc[car_dataframe.groupby(['Manufacturer'])['Sales_in_thousands'].idxmax()]
# dropping the Sales_in_thousands column as it is not available in the expected output of the question
best_selling_cars.drop('Sales_in_thousands',axis = 1,inplace = True)
best_selling_cars.reset_index(drop=True, inplace=True)

# converting car_dataframe to a csv file and setting the headers with the columns
best_selling_cars.to_csv('car.csv', index=False, header=best_selling_cars.columns)
print(best_selling_cars)

# function calls
getBestSellingCar()
getBestSellingCarByManufacturer("BMW")


  Manufacturer     Model
0        Acura        TL
1         Audi        A4
2          BMW      528i
3        Buick   Century
4     Cadillac   DeVille

The best selling car is 
  Manufacturer     Model  Sales_in_thousands
8        Buick   Century              91.561

The best selling car from the manufacturer BMW is 
  Manufacturer  Model
2          BMW   528i


In [48]:
car_dataframe

Manufacturer         Model  Sales_in_thousands
0         Acura       Integra              16.919
1         Acura            TL              39.384
2         Acura            RL               8.588
3          Audi            A4              20.397
4          Audi            A6              18.780
5          Audi            A8               1.380
6           BMW          328i               9.231
7           BMW          528i              17.527
8         Buick       Century              91.561
9         Buick         Regal              39.350
10        Buick   Park Avenue              27.851
11        Buick       LeSabre              83.257
12     Cadillac       DeVille              63.729
13     Cadillac       Seville              15.943
14     Cadillac      Eldorado               6.536
15     Cadillac        Catera              11.185
16     Cadillac      Escalade              14.785

In [84]:
best_selling_cars.to_csv('car.csv', index=False, header=best_selling_cars.columns)