In [1]:
# arithmetic with numpy-1D,2D array
# statistical measures on array-1D array
# stacking options-stack() and column_stack()

In [2]:
import numpy as np

In [4]:
a1=np.arange(21,39)
b1=np.arange(0.23,78.90) # the starting should should be error free.

In [5]:
a1

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38])

In [23]:
print(b1)

[ 0.23  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23 11.23
 12.23 13.23 14.23 15.23 16.23 17.23 18.23 19.23 20.23 21.23 22.23 23.23
 24.23 25.23 26.23 27.23 28.23 29.23 30.23 31.23 32.23 33.23 34.23 35.23
 36.23 37.23 38.23 39.23 40.23 41.23 42.23 43.23 44.23 45.23 46.23 47.23
 48.23 49.23 50.23 51.23 52.23 53.23 54.23 55.23 56.23 57.23 58.23 59.23
 60.23 61.23 62.23 63.23 64.23 65.23 66.23 67.23 68.23 69.23 70.23 71.23
 72.23 73.23 74.23 75.23 76.23 77.23 78.23]


In [8]:
a1+b1

ValueError: operands could not be broadcast together with shapes (18,) (79,) 

In [9]:
float('virus')

ValueError: could not convert string to float: 'virus'

In [10]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([10,20,30,40,50,60])

In [11]:
a1+a2

array([11, 22, 33, 44, 55, 66])

In [ ]:
# +, the arrays should numbers
     the arrays, the shape should the same==> dimensions should be the same
     arithmetic operations happen at respective indices

In [12]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([10,20,30,40,50,60])

In [13]:
a1-a2

array([ -9, -18, -27, -36, -45, -54])

In [14]:
a1*a2

array([ 10,  40,  90, 160, 250, 360])

In [15]:
a1/a2

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [16]:
a1%a2 # remainder

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [17]:
a1//a2 ==> #integers and not floating is preferred

array([0, 0, 0, 0, 0, 0], dtype=int32)

In [21]:
print(a1**a2)

[          1     1048576 -1010140999           0  1296002393           0]


In [19]:
a1-a2+a2/2*a2

array([  41.,  182.,  423.,  764., 1205., 1746.])

In [20]:
# order of precedence

In [ ]:
PEDMAS

In [24]:
pow(2,2)

4

In [25]:
pow(a1,a2) # inbuilt 69 functions of python works with arrays positionwise

array([          1,     1048576, -1010140999,           0,  1296002393,
                 0], dtype=int32)

In [29]:
b1

array([ 0.23,  1.23,  2.23,  3.23,  4.23,  5.23,  6.23,  7.23,  8.23,
        9.23, 10.23, 11.23, 12.23, 13.23, 14.23, 15.23, 16.23, 17.23,
       18.23, 19.23, 20.23, 21.23, 22.23, 23.23, 24.23, 25.23, 26.23,
       27.23, 28.23, 29.23, 30.23, 31.23, 32.23, 33.23, 34.23, 35.23,
       36.23, 37.23, 38.23, 39.23, 40.23, 41.23, 42.23, 43.23, 44.23,
       45.23, 46.23, 47.23, 48.23, 49.23, 50.23, 51.23, 52.23, 53.23,
       54.23, 55.23, 56.23, 57.23, 58.23, 59.23, 60.23, 61.23, 62.23,
       63.23, 64.23, 65.23, 66.23, 67.23, 68.23, 69.23, 70.23, 71.23,
       72.23, 73.23, 74.23, 75.23, 76.23, 77.23, 78.23])

In [30]:
sum([1,2,3,4])

10

In [31]:
sum(b1)

3099.170000000001

In [32]:
b1

array([ 0.23,  1.23,  2.23,  3.23,  4.23,  5.23,  6.23,  7.23,  8.23,
        9.23, 10.23, 11.23, 12.23, 13.23, 14.23, 15.23, 16.23, 17.23,
       18.23, 19.23, 20.23, 21.23, 22.23, 23.23, 24.23, 25.23, 26.23,
       27.23, 28.23, 29.23, 30.23, 31.23, 32.23, 33.23, 34.23, 35.23,
       36.23, 37.23, 38.23, 39.23, 40.23, 41.23, 42.23, 43.23, 44.23,
       45.23, 46.23, 47.23, 48.23, 49.23, 50.23, 51.23, 52.23, 53.23,
       54.23, 55.23, 56.23, 57.23, 58.23, 59.23, 60.23, 61.23, 62.23,
       63.23, 64.23, 65.23, 66.23, 67.23, 68.23, 69.23, 70.23, 71.23,
       72.23, 73.23, 74.23, 75.23, 76.23, 77.23, 78.23])

In [34]:
b1.max()

78.23

In [35]:
b1.min()

0.23

In [36]:
b1.mean()

39.230000000000004

In [38]:
b1

array([ 0.23,  1.23,  2.23,  3.23,  4.23,  5.23,  6.23,  7.23,  8.23,
        9.23, 10.23, 11.23, 12.23, 13.23, 14.23, 15.23, 16.23, 17.23,
       18.23, 19.23, 20.23, 21.23, 22.23, 23.23, 24.23, 25.23, 26.23,
       27.23, 28.23, 29.23, 30.23, 31.23, 32.23, 33.23, 34.23, 35.23,
       36.23, 37.23, 38.23, 39.23, 40.23, 41.23, 42.23, 43.23, 44.23,
       45.23, 46.23, 47.23, 48.23, 49.23, 50.23, 51.23, 52.23, 53.23,
       54.23, 55.23, 56.23, 57.23, 58.23, 59.23, 60.23, 61.23, 62.23,
       63.23, 64.23, 65.23, 66.23, 67.23, 68.23, 69.23, 70.23, 71.23,
       72.23, 73.23, 74.23, 75.23, 76.23, 77.23, 78.23])

In [39]:
b1.sort() # ascending order is preferred

In [43]:
b1

array([ 0.23,  1.23,  2.23,  3.23,  4.23,  5.23,  6.23,  7.23,  8.23,
        9.23, 10.23, 11.23, 12.23, 13.23, 14.23, 15.23, 16.23, 17.23,
       18.23, 19.23, 20.23, 21.23, 22.23, 23.23, 24.23, 25.23, 26.23,
       27.23, 28.23, 29.23, 30.23, 31.23, 32.23, 33.23, 34.23, 35.23,
       36.23, 37.23, 38.23, 39.23, 40.23, 41.23, 42.23, 43.23, 44.23,
       45.23, 46.23, 47.23, 48.23, 49.23, 50.23, 51.23, 52.23, 53.23,
       54.23, 55.23, 56.23, 57.23, 58.23, 59.23, 60.23, 61.23, 62.23,
       63.23, 64.23, 65.23, 66.23, 67.23, 68.23, 69.23, 70.23, 71.23,
       72.23, 73.23, 74.23, 75.23, 76.23, 77.23, 78.23])

In [44]:
b1.shape

(79,)

In [45]:
# reshape this array and let us know your conclusion

In [ ]:
79
1 79==>prime number

In [46]:
b1.reshape(1,79)

array([[ 0.23,  1.23,  2.23,  3.23,  4.23,  5.23,  6.23,  7.23,  8.23,
         9.23, 10.23, 11.23, 12.23, 13.23, 14.23, 15.23, 16.23, 17.23,
        18.23, 19.23, 20.23, 21.23, 22.23, 23.23, 24.23, 25.23, 26.23,
        27.23, 28.23, 29.23, 30.23, 31.23, 32.23, 33.23, 34.23, 35.23,
        36.23, 37.23, 38.23, 39.23, 40.23, 41.23, 42.23, 43.23, 44.23,
        45.23, 46.23, 47.23, 48.23, 49.23, 50.23, 51.23, 52.23, 53.23,
        54.23, 55.23, 56.23, 57.23, 58.23, 59.23, 60.23, 61.23, 62.23,
        63.23, 64.23, 65.23, 66.23, 67.23, 68.23, 69.23, 70.23, 71.23,
        72.23, 73.23, 74.23, 75.23, 76.23, 77.23, 78.23]])

In [47]:
b1.reshape(79,1)

array([[ 0.23],
       [ 1.23],
       [ 2.23],
       [ 3.23],
       [ 4.23],
       [ 5.23],
       [ 6.23],
       [ 7.23],
       [ 8.23],
       [ 9.23],
       [10.23],
       [11.23],
       [12.23],
       [13.23],
       [14.23],
       [15.23],
       [16.23],
       [17.23],
       [18.23],
       [19.23],
       [20.23],
       [21.23],
       [22.23],
       [23.23],
       [24.23],
       [25.23],
       [26.23],
       [27.23],
       [28.23],
       [29.23],
       [30.23],
       [31.23],
       [32.23],
       [33.23],
       [34.23],
       [35.23],
       [36.23],
       [37.23],
       [38.23],
       [39.23],
       [40.23],
       [41.23],
       [42.23],
       [43.23],
       [44.23],
       [45.23],
       [46.23],
       [47.23],
       [48.23],
       [49.23],
       [50.23],
       [51.23],
       [52.23],
       [53.23],
       [54.23],
       [55.23],
       [56.23],
       [57.23],
       [58.23],
       [59.23],
       [60.23],
       [61.23],
       [

In [ ]:
in numpy, when we face prime numbers, the arrays can only be shapes into row/column matri depecting on their factors

In [50]:
a1

array([1, 2, 3, 4, 5, 6])

In [51]:
a1+2 # add 2 to each and every index value

array([3, 4, 5, 6, 7, 8])

In [52]:
[1,2,3,4]+[4,5] # python limitation

[1, 2, 3, 4, 4, 5]

In [69]:
z1=np.array([[67,67,100],[123,456,789]])

In [70]:
z1

array([[ 67,  67, 100],
       [123, 456, 789]])

In [71]:
z2=np.array([[12,78,56],[78,90,343]])   

In [72]:
z2

array([[ 12,  78,  56],
       [ 78,  90, 343]])

In [73]:
z1+z2

array([[  79,  145,  156],
       [ 201,  546, 1132]])

In [74]:
z1.mean()

267.0

In [75]:
z1.max()

789

In [76]:
z1

array([[ 67,  67, 100],
       [123, 456, 789]])

In [77]:
z1.argmax()

5

In [78]:
z1.argmin()

0

In [79]:
z1

array([[ 67,  67, 100],
       [123, 456, 789]])

In [80]:
z2

array([[ 12,  78,  56],
       [ 78,  90, 343]])

In [86]:
np.stack((z1,z2))

array([[[ 67,  67, 100],
        [123, 456, 789]],

       [[ 12,  78,  56],
        [ 78,  90, 343]]])

In [87]:
np.column_stack((z1,z2))

array([[ 67,  67, 100,  12,  78,  56],
       [123, 456, 789,  78,  90, 343]])

In [88]:
# axis=0 means a row
# axis =1 means a column