In [1]:
# hstack and vstack
# pandas introduction
# inclass day 1 lab

In [2]:
import numpy as np
a1=np.array([[1,2],
           [3,4]])

In [3]:
a1

array([[1, 2],
       [3, 4]])

In [4]:
a1.ndim

2

In [5]:
a2=np.array([[1,2],
           [3,4]])

In [6]:
a2

array([[1, 2],
       [3, 4]])

In [7]:
np.hstack((a1,a2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [8]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [9]:
a

NameError: name 'a' is not defined

In [10]:
a[0]

NameError: name 'a' is not defined

In [11]:
import pandas as pd
import numpy as np
filter.warnings

In [ ]:
# pandas is a data analysis library of python
1. easy of handling
2. csv,xcel,sql,rtf,gbq etc(structured data)
3. pandas-1.SEries 2. Dataframe

In [12]:
# data preparation for creating series
index=['a','b','c','d','e']
data=[10,20,30,40,50]
data1={2,3,4,5,6}
array=np.array([100,200,300,400,500])#static array
d1={'a1':23,'b1':56,'c1':78,'d1':98,'e1':90}

In [13]:
a=pd.Series(data=data) # create series from python list

In [14]:
b=pd.Series(data=data,index=index)# create series from python list

In [15]:
pd.Series(data=data1) # doest not work because it is unordered

TypeError: 'set' type is unordered

In [16]:
c=pd.Series(data=d1) # keys have been converted to indices and data remains the same

In [18]:
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [19]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
c

a1    23
b1    56
c1    78
d1    98
e1    90
dtype: int64

In [21]:
type(a)

pandas.core.series.Series

In [22]:
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [23]:
a[0]

10

In [24]:
a[4]

50

In [25]:
a[-1] # negative indices not allowed

KeyError: -1

In [26]:
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [27]:
a[[0,1,3]] # to extract data out from 2D, double square brackets is req

0    10
1    20
3    40
dtype: int64

In [28]:
a[[3,1,0]] # reversing the extraction is allowed

3    40
1    20
0    10
dtype: int64

In [29]:
# what if i want to change a data elemeny here/

In [ ]:
a

In [30]:
a[1]=100 # pandas series is mutable because it made of list, hence making it mutable

In [31]:
a

0     10
1    100
2     30
3     40
4     50
dtype: int64

In [ ]:
a[0:2]

In [ ]:
# broadcasting

In [ ]:
a[0:2]=100.78776

In [ ]:
a

In [37]:
ser1=pd.Series(data=array,index=['USA','USSR','IND','JAP','AUS']) 

In [38]:
ser2=pd.Series(data=array,index=['USA','SPAIN','IND','JAP','UK']) 

In [39]:
ser1

USA     100
USSR    200
IND     300
JAP     400
AUS     500
dtype: int32

In [40]:
ser2

USA      100
SPAIN    200
IND      300
JAP      400
UK       500
dtype: int32

In [45]:
result=ser1+ser2
result

AUS        NaN
IND      600.0
JAP      800.0
SPAIN      NaN
UK         NaN
USA      200.0
USSR       NaN
dtype: float64

In [ ]:
ser1-ser2

In [ ]:
ser1*ser2

In [ ]:
ser1/ser2

In [ ]:
ser1**ser2

In [ ]:
1/0

In [32]:
ai=np.array([1,2])
bi=np.array([0,1])
ai/bi


C:\Users\SHAMBHAVI\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([inf,  2.])

In [33]:
# pandas data frame

In [34]:
import pandas as pd
import numpy as np

In [42]:
ser1ok

USA     100
USSR    200
IND     300
JAP     400
AUS     500
dtype: int32

In [47]:
pd.DataFrame(data=result,columns=['Final value'])

Final value
AUS            NaN
IND          600.0
JAP          800.0
SPAIN          NaN
UK             NaN
USA          200.0
USSR           NaN

In [55]:
new=pd.DataFrame(data=[56,25,100],index=['Corona virus deaths','total cured cases','total population'],columns=['Total'])

In [56]:
new

Total
Corona virus deaths     56
total cured cases       25
total population       100

In [58]:
a1 = np.arange(2,11,2)

a2 = np.arange(22,31,2)

np.stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [74]:
a1 = np.arange(2,11,2)

a2 = np.arange(22,31,2)

np.column_stack((a1,a2))
print(a1)

[ 2  4  6  8 10]


In [60]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [61]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [70]:
pd.Series(data=np.random.randn(10)) #dynamic series

0    1.107527
1    1.081625
2    0.641555
3   -0.247471
4    1.088913
5   -0.911618
6    0.009481
7    0.329133
8   -1.445975
9    0.024794
dtype: float64

In [72]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [73]:
np.linspace(0,50,25)

array([ 0.        ,  2.08333333,  4.16666667,  6.25      ,  8.33333333,
       10.41666667, 12.5       , 14.58333333, 16.66666667, 18.75      ,
       20.83333333, 22.91666667, 25.        , 27.08333333, 29.16666667,
       31.25      , 33.33333333, 35.41666667, 37.5       , 39.58333333,
       41.66666667, 43.75      , 45.83333333, 47.91666667, 50.        ])

In [75]:
a1

array([ 2,  4,  6,  8, 10])

In [76]:
print(a1)

[ 2  4  6  8 10]
