In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('train.csv')

In [6]:
a = df.sort_values(by = 'Fare')

In [7]:
a

PassengerId  Survived  Pclass                                Name  \
271          272         1       3        Tornquist, Mr. William Henry   
597          598         0       3                 Johnson, Mr. Alfred   
302          303         0       3     Johnson, Mr. William Cahoone Jr   
633          634         0       1       Parr, Mr. William Henry Marsh   
277          278         0       2         Parkes, Mr. Francis "Frank"   
..           ...       ...     ...                                 ...   
438          439         0       1                   Fortune, Mr. Mark   
341          342         1       1      Fortune, Miss. Alice Elizabeth   
737          738         1       1              Lesurer, Mr. Gustave J   
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
271    male  25.0      0      0      LINE    0.0000          NaN        S  
597    male  49.0      0      0      LINE    0.0000          NaN        S  
302    male  19.0      0      0      LINE    0.0000          NaN        S  
633    male   NaN      0      0    112052    0.0000          NaN        S  
277    male   NaN      0      0    239853    0.0000          NaN        S  
..      ...   ...    ...    ...       ...       ...          ...      ...  
438    male  64.0      1      4     19950  263.0000  C23 C25 C27        S  
341  female  24.0      3      2     19950  263.0000  C23 C25 C27        S  
737    male  35.0      0      0  PC 17755  512.3292         B101        C  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  

[891 rows x 12 columns]

In [8]:
a = a['Fare']

In [10]:
a.unique()

array([  0.    ,   4.0125,   5.    ,   6.2375,   6.4375,   6.45  ,
         6.4958,   6.75  ,   6.8583,   6.95  ,   6.975 ,   7.0458,
         7.05  ,   7.0542,   7.125 ,   7.1417,   7.225 ,   7.2292,
         7.25  ,   7.3125,   7.4958,   7.5208,   7.55  ,   7.6292,
         7.65  ,   7.725 ,   7.7292,   7.7333,   7.7375,   7.7417,
         7.75  ,   7.775 ,   7.7875,   7.7958,   7.8   ,   7.8292,
         7.8542,   7.875 ,   7.8792,   7.8875,   7.8958,   7.925 ,
         8.0292,   8.05  ,   8.1125,   8.1375,   8.1583,   8.3   ,
         8.3625,   8.4042,   8.4333,   8.4583,   8.5167,   8.6542,
         8.6625,   8.6833,   8.7125,   8.85  ,   9.    ,   9.2167,
         9.225 ,   9.35  ,   9.475 ,   9.4833,   9.5   ,   9.5875,
         9.825 ,   9.8375,   9.8417,   9.8458,  10.1708,  10.4625,
        10.5   ,  10.5167,  11.1333,  11.2417,  11.5   ,  12.    ,
        12.275 ,  12.2875,  12.35  ,  12.475 ,  12.525 ,  12.65  ,
        12.875 ,  13.    ,  13.4167,  13.5   ,  13.7917,  13.8

In [23]:
b = df.sort_values(by = 'Fare',ascending=False)['Fare'].unique()

In [22]:
b

array([512.3292, 247.5208, 211.5   , 153.4625, 135.6333, 120.    ,
       108.9   ,  91.0792,  86.5   ,  82.1708,  79.65  ,  78.2667,
        76.7292,  73.5   ,  69.55  ,  65.    ,  61.3792,  57.9792,
        56.4958,  55.    ,  52.    ,  50.4958,  49.5   ,  42.4   ,
        39.6875,  39.    ,  36.75  ,  34.6542,  33.5   ,  32.3208,
        31.    ,  30.0708,  29.125 ,  28.5   ,  27.7208,  26.3875,
        26.25  ,  25.925 ,  24.15  ,  23.25  ,  22.3583,  21.075 ,
        20.525 ,  19.9667,  18.7875,  17.8   ,  16.1   ,  15.85  ,
        15.55  ,  15.1   ,  15.    ,  14.4542,  14.    ,  13.7917,
        13.    ,  12.525 ,  12.2875,  11.5   ,  10.5167,  10.1708,
         9.8375,   9.5   ,   9.35  ,   9.    ,   8.6833,   8.5167,
         8.4042,   8.1583,   8.05  ,   7.8958,   7.875 ,   7.8   ,
         7.775 ,   7.7375,   7.725 ,   7.55  ,   7.3125,   7.225 ,
         7.0542,   6.975 ,   6.75  ,   6.4375,   4.0125])

In [24]:
c = df.sort_values(by = 'Fare',ascending=False)['Fare'].unique()[2:3]

In [25]:
c

array([262.375])